setwd("C:/Users/18904/Github/singapore/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/1-plot.RData")){
  p=2;n=7;library(SFDesign)
  D=maximinLHD(n,p)$design
  save(D,n,file="data/1-plot.RData")
}
load("data/1-plot.RData")
pdf("../figures/1.pdf",width=4,height=4)
oldpar=par(mar=c(1,1,1,1))
plot(D,pch=16,cex=1.4,col="#222222",axes=FALSE,xlim=c(0,1),ylim=c(0,1),asp=1)
for(i in 1:(n+1)){
  segments(0,(i-1)/n,1,(i-1)/n,col="#bbbbbb",lwd=0.6)
  segments((i-1)/n,0,(i-1)/n,1,col="#bbbbbb",lwd=0.6)
}
box(col="#666666",lwd=0.8)
par(oldpar)
dev.off()