setwd("C:/Users/18904/Github/singapore/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
e=new.env();load("data/ablation-summary.RData",envir=e);tab=e$tab
pdf("../figures/4.pdf",width=4,height=4)
oldpar=par(mar=c(2,3,1,1),mgp=c(1.5,0.5,0))
dims=c("d1","d2","d4")
v=rbind("with screening"=as.numeric(tab[tab$config=="M1",dims]),"no screening"=as.numeric(tab[tab$config=="S2",dims]))
barplot(v,beside=TRUE,names.arg=c("1-D","2-D","4-D"),col=c("#555555","#222222"),border=NA,ylab="median found minimum f*",cex.axis=0.8,cex.names=0.9)
abline(h=0,lty=2)
legend("topright",c("with screening","no screening"),fill=c("#555555","#222222"),border=NA,bty="n",cex=0.7)
box(col="#666666",lwd=0.8)
par(oldpar)
dev.off()
