setwd("C:/Users/18904/Github/singapore/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
e=new.env();load("data/ablation-summary.RData",envir=e);tab=e$tab
pdf("../figures/4.pdf",width=4,height=4)
oldpar=par(mar=c(3.2,3.6,2.8,0.8),mgp=c(2.2,0.6,0))
dims=c("d1","d2","d4")
v=rbind("with screening (M1)"=as.numeric(tab[tab$config=="M1",dims]),"no screening (S2)"=as.numeric(tab[tab$config=="S2",dims]))
barplot(v,beside=TRUE,names.arg=c("1-D","2-D","4-D"),col=c("#555555","#222222"),border=NA,ylab="median found minimum  f*  (lower is better)",cex.axis=0.8,cex.names=0.9)
mtext("Screening hurts",side=3,line=0.6,cex=0.85,font=2)
legend("topright",c("with screening (M1)","no screening (S2)"),fill=c("#555555","#222222"),border=NA,bty="n",cex=0.7)
box(col="#666666",lwd=0.8)
par(oldpar)
dev.off()
