setwd("C:/Users/18904/Github/singapore/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
e=new.env();load("data/ablation-summary.RData",envir=e);tab=e$tab
pdf("../figures/5.pdf",width=4,height=4)
oldpar=par(mar=c(2,3,1,1),mgp=c(1.5,0.5,0))
dims=c("d1","d2","d4")
v=rbind("with screening"=as.numeric(tab[tab$config=="M1",dims]),"no screening"=as.numeric(tab[tab$config=="S2",dims]))
ord=c("M1","S2","S1","M0")
v8=as.numeric(tab[tab$config %in% ord,"d8"]);names(v8)=tab$config[tab$config %in% ord];v8=v8[ord]
barplot(v8,col=c("#555555","#222222","#888888","#bbbbbb"),border=NA,names.arg=c("M1","S2","S1","M0"),ylab="found minimum f* at 8-D",cex.axis=0.8,cex.names=0.9,ylim=c(0,22))
abline(h=0,lty=2)
box(col="#666666",lwd=0.8)
par(oldpar)
dev.off()
